base: '/'
rootPageId: 1
languages:
  - title: English
    enabled: true
    languageId: 0
    base: '/'
    typo3Language: default
    locale: en-US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    flag: us
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      'movies.json': 100
      'snacks.json': 101
      'screenings.json': 102
